cve: CVE-2017-0358
attack_vector: local

os:
  name: ubuntu
  version: 16.04.1
software:
  - name: ntfs-3g
    version: 1:2015.3.14AR.1-1build1
    os_depend: true
caution:
  - type: setup
    msg: 
      - at least two CPU cores.
