cve: CVE-2016-8655
attack_vector: local

os:
  name: ubuntu
  version: 16.04.1
reload: true
software:
  - name: linux-image
    version: 4.4.0-51-generic
    os_depend: true
    affect_kernel: true
caution:
  - type: setup
    msg: 
      - at least two CPU cores.
