cve: CVE-2014-6271
attack_vector: remote

os:
  name: centos
  version: 6.5
software:
  - name: gcc
    os_depend: true
  - name: make
    os_depend: true
  - name: pcre
    os_depend: true
  - name: pcre-devel
    os_depend: true
  - name: wget
    os_depend: true
  - name: apache_httpd
    version: 2.2.15
    configure_command: "./configure --prefix=/opt/httpd"
    os_depend: false
    src_dir: false
setting: setting/CVE-2014-6271/shellshock
