---
- name: put rails app
  copy:
    src: ../files/server
    dest: /home/rails
    owner: rails
    mode: 0644
- name: command bundle
  shell: bash -lc "bundle"
  args:
    chdir: /home/rails/server
  become_user: rails
- name: rails s -b 192.168.33.10
  shell: bash -lc "rails s -d -b 192.168.33.10"
  args:
    chdir: /home/rails/server
  become_user: rails
